// Access node.js's built in http, url, fs, path, and event modules
const http = require('http');
const url = require('url');                                                        // Can be used to split up a web address into readable parts (use q = url.parse(...).query to return a URL object with each part of the address as properties [example address: localhost:8000/default.htm?year=2017&month=february], also has .host [localhost:8000], .pathname [default.htm], and .search [?year=2017&month=february])
const formidable = require('formidable');                                          // Used to process form data and especially helpful for file uploads
const fs = require('fs');                                                          // Will be used to work with file system operations (read, create, update, etc.); needed to dynamically display reports generated by the DB
const path = require('path');                                                      // Used to generate the correct file paths
const sql = require('mssql');                                                      // Used to connect to our Database
const events = require('events');                                                  // Used to create-, fire-, and listen for- our own events (i.e. user likes a song, etc.)
const queryString = require('querystring');                                        // Used to parse strinfs into JavaScript objects


// Here you can include any other built in / user modules as well (think #include <...>)
// const dt = require('./myFirstModule');
const dbConfig = require('./databaseConfig');

// Event creation and event handlers
const eventEmitter = new events.EventEmitter();                                    // All event properties and methods are an instance of this eventEmitter object
/*
//Creates an event handler:
var myEventHandler = function () {
  console.log('I hear a scream!');
}
  
//Assign the event handler to an event:
eventEmitter.on('scream', myEventHandler);
  
//Fire the 'scream' event:
eventEmitter.emit('scream');
*/

// Function to handle database connection errors
function handleDatabaseError(res, error) {
    console.error('Database connection error:', error);
    res.writeHead(500, { 'Content-Type': 'text/plain' });
    res.end('Database connection error');
}

// Generate a random session ID (you might need a more secure method in production)
function generateSessionID() {
    return Math.random().toString(36).substring(2, 15);
}

// Serve either: only the html file (1), html + css files (2), html + js files(3), or html + css + js files (4):
// serveFile(res, 1, writeHeadParameters, htmlPath);
// serveFile(res, 2, writeHeadParameters, htmlPath, cssFileName);
// serveFile(res, 3, writeHeadParameters, htmlPath, jsFileName);
// serveFile(res, 4, writeHeadParameters, htmlPath, cssFileName, jsFileName);
function serveFile(res, mode, writeHeadParameters, filePath, cssFileName, jsFileName) {
    fs.readFile(filePath, 'utf-8', function(err, data) {
        if (err) {
            console.log('File not found:', filePath);
            res.writeHead(404, { 'Content-Type': 'text/plain' });
            res.end('File not found');
        } 

        // Serve HTML file with potentially a css and js file appended to it
        else {
            //console.log("mode: ", mode);
            //console.log("writeHeadParameters...: ", ...writeHeadParameters);
            res.writeHead(...writeHeadParameters);
            res.write(data);
            
            // Append css content
            if (mode === 2) {
                //console.log("2: ", mode);
                const cssPath = path.join(__dirname, '..', 'client', cssFileName);
                fs.readFile(cssPath, 'utf-8', function(err, cssData) {
                    if (!err) {
                        res.write('\n<style>\n' + cssData + '\n</style>');
                    }
                    else {
                        console.error('Error reading CSS file (2):', err);
                    }
                });
            }

            // Append js content
            else if (mode === 3) {
                //console.log("3: ", mode);
                const jsPath = path.join(__dirname, '..', 'client', jsFileName);
                fs.readFile(jsPath, 'utf-8', function(err, jsData) {
                    if (!err) {
                        res.write('\n<script>\n' + jsData + '\n</script>');
                    }
                    else {
                        console.error('Error reading JS file (3):', err);
                    }
                });
            }
            
            // Append both cs and js content
            else if (mode === 4) {
                //console.log("4: ", mode);
                const cssPath = path.join(__dirname, '..', 'client', cssFileName);
                fs.readFile(cssPath, 'utf-8', function(err, cssData) {
                    if (!err) {
                            res.write('\n<style>\n' + cssData + '\n</style>');
                    }
                    else {
                        console.error('Error reading CSS file (4):', err);
                    }

                    // Serve assosciated js file
                    const jsPath = path.join(__dirname, '..', 'client', jsFileName);
                    fs.readFile(jsPath, 'utf-8', function(err, jsData) {
                            if (!err) {
                                res.write('\n<script>\n' + jsData + '\n</script>');
                            }
                            else {
                                console.error('Error reading js file (4):', err);
                            }
                    })
                })
            }
            res.end();
        }
    });
}

// Takes in login credentials against database for authentication; returns Cougar_ID
function isValidAccount(username, userPass, callback) {
    sql.connect(dbConfig, (err) => {
        // Database connection error handler
        if (err) {
            handleDatabaseError(res, err);
            return;                    
        }

        const request = new sql.Request();

        const selectStatement = 
        'SELECT A.Cougar_ID ' +
        'FROM MusicLibrary.[User] A ' +
        'WHERE A.Username = @username ' +
        'AND A.Pass = @userPass';

        // Adds parameters to the select statement
        request.input('username', sql.VarChar, username);
        request.input('userPass', sql.VarChar, userPass);
        
        request.query(selectStatement, (err, result) =>  {
            if (err) {                                                   // Database query error handler
                console.error('Database query error:', err);
                sql.close();
                callback('Database query error', null);
                return;
            }

            // Process query result and close
            const row = result.recordset && result.recordset[0];
            const userID = row ? row.Cougar_ID : null;
            console.log('userID from isValidAccount():', userID);
            sql.close();

            // Pass rolename to the callback for role validation
            callback(null, userID);
        })
    })
}

// Updates listener table with login time
function updateLastLogin(userID, callback) {
    sql.connect(dbConfig, (err) => {
        // Database connection error handler
        if (err) {
            handleDatabaseError(res, err);
            return;                    
        }
        const loginTime = new Date();
        const request = new sql.Request();

        const selectStatement = 
        `UPDATE MusicLibrary.[Listener]
        SET Last_Login_Time = @loginTime
        WHERE Cougar_ID = @userID;`

        // Adds parameters to the select statement
        request.input('loginTime', sql.DateTime2, loginTime);
        request.input('userID', sql.Int, userID);
        
        request.query(selectStatement, (err, result) =>  {
            if (err) {                                                   // Database query error handler
                console.error('Database query error:', err);
                sql.close();
                callback('Database query error', null);
                return;
            }

            // Process query result and close
            sql.close();
            // Pass login time to callback
            callback(null, loginTime);
        })
    })
}

// Updates listener table with login time
function getRecommendedAlbum(userID, callback) {
    sql.connect(dbConfig, (err) => {
        // Database connection error handler
        if (err) {
            handleDatabaseError(res, err);
            return;                    
        }
        const request = new sql.Request();
        const selectStatement = 
        'SELECT A.Album_ID ' +
        'FROM MusicLibrary.[Recommended_Album] A ' +
        'WHERE Cougar_ID = @userID ';

        // Adds parameters to the select statement
        request.input('userID', sql.Int, userID);
        
        request.query(selectStatement, (err, result) =>  {
            if (err) {                                                   // Database query error handler
                console.error('Database query error:', err);
                sql.close();
                callback('Database query error', null);
                return;
            }

            // Process query result and close
            const row = result.recordset && result.recordset[0];
            const albumID = row ? row.Album_ID : null;
            //console.log('albumID from getRecommendedAlbum():', albumID);
            sql.close();

            // Pass login time to callback
            callback(null, albumID);
        })
    })
}

// Returns a given Cougar_ID's role
function getUserRole(userID, callback) {
    sql.connect(dbConfig, (err) => {
        // Database connection error handler
        if (err) {
            handleDatabaseError(res, err);
            return;                    
        }

        const request = new sql.Request();

        const selectStatement = 
        'SELECT A.Role_Name ' +
        'FROM MusicLibrary.[Roles] A, MusicLibrary.[User] B ' +
        'WHERE A.Role_ID = B.Role_ID ' +
        'AND B.Cougar_ID = @userID';

        // Adds in parameter userID as int to select statement
        request.input('userID', sql.Int, userID);
        
        request.query(selectStatement, (err, result) =>  {
            if (err) {                                                   // Database query error handler
                console.error('Database query error:', err);
                sql.close();
                callback('Database query error', null);
                return;
            }

            // Process query result and close
            const row = result.recordset && result.recordset[0];
            const roleName = row ? row.Role_Name : null;
            console.log('rolename from getUserRole(): ', roleName);
            sql.close();

            // Pass rolename to the callback for role validation
            callback(null, roleName);
        })
    })
}

// Returns the name corresponding to a Cougar_ID
function getUserName(userID, callback) {
    sql.connect(dbConfig, (err) => {
        // Database connection error handler
        if (err) {
            handleDatabaseError(res, err);
            return;                    
        }

        const request = new sql.Request();

        const selectStatement = 
        'SELECT A.Username ' +
        'FROM MusicLibrary.[User] A ' +
        'WHERE A.Cougar_ID = @userID';

        // Adds in parameter userID as int to select statement
        request.input('userID', sql.Int, userID);
        
        request.query(selectStatement, (err, result) =>  {
            if (err) {                                                   // Database query error handler
                console.error('Database query error:', err);
                sql.close();
                callback('Database query error', null);
                return;
            }

            // Process query result and close
            const row = result.recordset && result.recordset[0];
            const username = row ? row.Username : null;
            console.log('username from getUserName(): ', username);
            sql.close();

            // Pass username to the callback for role validation
            callback(null, username);
        })
    })
}

function redirectToLoginPage(res) {
    const htmlPath = path.join(__dirname, '..', 'client', 'login.html');
    const cssFileName = 'login.css';
    const jsFileName = 'login.js';
    const writeHeadParameters = [302, { 'Content-Type': 'text/html; charset=utf-8' }];

    serveFile(res, 1, writeHeadParameters, htmlPath);
}

function redirectToMainPage(res) {
    const htmlPath = path.join(__dirname, '..', 'client', 'index.html');
    const cssFileName = 'mainPage.css';
    const jsFileName = 'mainPage.js';
    const writeHeadParameters = [302, { 'Content-Type': 'text/html; charset=utf-8' }];

    serveFile(res, 4, writeHeadParameters, htmlPath, cssFileName, jsFileName);
}

function redirectToMusicUpload(res) {
    const htmlPath = path.join(__dirname, '..', 'client', 'musicUpload.html');
    const writeHeadParameters = [302, { 'Content-Type': 'text/html; charset=utf-8' }];

    serveFile(res, 1, writeHeadParameters, htmlPath);
}

// Returns userID from a cookie, if session exists
function getIdFromCookie(userCookie) {
    if (userCookie && userCookie.includes('sessionID')) {
        const sessionID = userCookie.split('=')[1];
        
        if (sessions[sessionID]) {
            return sessions[sessionID].user;
        }
        
        else {
            console.error(`Session not found for sessionID: ${sessionID}`);
        }
    }

    return undefined;
}

// To be used first on any page past the login; checks the user's cookies to get their session and ensures the session exists in server memory, else redirects user back to login page
function authenticateSession(req, res, user) {
    const userCookie = req.headers.cookie;

    user.id = getIdFromCookie(userCookie);

    // Cannot get user from session / session doesn't exist; send user to login page
    if (user.id === undefined) {
        redirectToLoginPage(res);
        return false;
    }
    
    return true;
}

// Session storage
const sessions = {};

//console.log('All Session/UserID Pairs:');
//for (const sessionID in sessions) {
//    if (sessions.hasOwnProperty(sessionID)) {
//        const userID = sessions[sessionID].user;
//        console.log(`SessionID: ${sessionID}, UserID: ${userID}`);
//    }
//}

// Creates a server object
const server = http.createServer(function(req, res) {                            // req - request from client as an object; res - response from server as an object
    const protocol = req.socket.encrypted ? 'https' : 'http';
    const baseURL = protocol + '://' + req.headers.host + '/';
    const reqUrl = new URL(req.url, baseURL);

    var fileName = reqUrl.pathname;
    
    if (req.method === 'POST') {
        console.log('File path for POST request:', fileName);

        // Initial login page where we authenticate users and generate sessionIDs for them
        if (fileName === '/login/landing') {
            // Login route
            let body = '';
            req.on('data', (data) => {
                body += data.toString();
            });

            req.on('end', () => {
                // postData example: username=john_doe&password=secretpassword
                // Parses login data from the body into username and pass to then authenticate the login and create / update their session
                const postData = queryString.parse(body);
                const username = postData.username;
                const userPass = postData.password;
                var userID;
                
                // Perform authentication of username and password
                isValidAccount(username, userPass, (err, userID) => {
                    // Database connection error handler
                    if (err) {
                        handleDatabaseError(res, err);
                        return;                    
                    }
                    
                    // This branch executes if userID is either null, undefined, 0, false, or an empty string (i.e. no records for given combination of username and password); need to redirect back to login page
                    else if (!userID) {
                        console.error('Authentication error. Please sign in with correct credentials');
                        /*
                        const htmlPath = path.join(__dirname, '..', 'client', 'login.html');
                        const cssFileName = 'login.css';
                        const jsFileName = 'login.js';
                        const writeHeadParameters = [200, { 'Content-Type': 'text/html; charset=utf-8' }];

                        serveFile(res, 1, writeHeadParameters, htmlPath);
                        */
                        redirectToLoginPage(res);
                        return;
                    }

                    // Updates last login time to work with DB trigger (show user new recommended albums)
                    let loginTime;
                    updateLastLogin(userID, (err, loginTime) => {
                        console.log('Login time: ', loginTime);
                    })

                    // Check if an existing session exists for the user via an existing cookie
                    const userCookie = req.headers.cookie;
                    console.log('req.headers.cookie: ' + userCookie);

                    if (userCookie && userCookie.includes('sessionID')) {
                        const sessionID = userCookie.split('=')[1];

                        // Remove existing sessionID
                        if (sessions[sessionID]) {                    
                            delete sessions[sessionID];
                        }
                    }

                    // Generate a new session ID for the current user request
                    const sessionID = generateSessionID();

                    // Create a new session for the user
                    sessions[sessionID] = { user: userID, sessionID: sessionID };
                    console.log('Current session: ' + sessionID);

                    console.log('Redirecting user to /index.html');

                    // Serve index.html
                    const htmlPath = path.join(__dirname, '..', 'client', 'index.html');
                    fs.readFile(htmlPath, function(err, data) {
                        if (err) {
                            res.writeHead(404, {'Content-Type': 'text/plain'});
                            res.end('File not found');
                        }
                        else {
                            res.writeHead(200, {'Content-Type': 'text/html', 'Set-Cookie': `sessionID=${sessionID}; Path=/`});
                            res.write(data);

                            // Serve assosciated css file
                            const cssPath = path.join(__dirname, '..', 'client', 'mainPage.css');
                            fs.readFile(cssPath, 'utf-8', function(err, cssData) {
                                if (!err) {
                                    res.write('\n<style>\n' + cssData + '\n</style>');
                                }
                                else {
                                    console.error('Error reading CSS file:', err);
                                }

                                // Serve assosciated js file
                                const jsPath = path.join(__dirname, '..', 'client', 'mainPage.js');
                                fs.readFile(jsPath, 'utf-8', function(err, jsData) {
                                    if (!err) {
                                        res.write('\n<script>\n' + jsData + '\n</script>');
                                    }
                                    else {
                                        console.error('Error reading js file:', err);
                                    }
                                    
                                    // End the response
                                    res.end();
                                })
                            })
                        }
                    });

                    // Directs logged in user to main page
                    /*
                    const indexHtmlPath = path.join(__dirname, '..', 'client', 'index.html');
                    const indexCssFileName = 'mainPage.css';
                    const indexJsFileName = 'mainPage.js';
                    const writeHeadParameters = [200, {
                        'Content-Type': 'text/html',
                        'Set-Cookie': `sessionID=${sessionID}; Path=/`
                    }];

                    serveFile(res, 4, writeHeadParameters, indexHtmlPath, indexCssFileName, indexJsFileName);
                    */
                })
            })
            return;
        }

        else if (fileName === '/artistDataEntry/single') {
            // Data parsing
            let body = '';
            req.on('data', (data) => {
                body += data.toString();
            });

            // Attempts to authenticate a user's session; if not authentic (session doesn't match server memory, or session doesn't exist) then user is sent to login page
            // Also retrieves userID if session in cookie matches session in memory
            const user = { id: undefined };
            let certified = authenticateSession(req, res, user);

            if (!certified) {
                return;
            }

            var userID = user.id;

            // Data Validation 
            const form = new formidable.IncomingForm({
                // Allow empty files when parsing form
                allowEmptyFiles: true,
                minFileSize: 0
            });

            //form.uploadDir = __dirname + '/uploads';

                form.parse(req, (err, fields, files) => {
                    if (err) {
                        console.error('Error parsing form:', err);
                        res.writeHead(500, { 'Content-Type': 'text/plain' });
                        res.end('Internal Server Error');
                        return;
                    }

                    // Security authentication (user must be an artist)
                    getUserRole(userID, (err, roleName) => {
                        // Database connection error handler
                        if (err) {
                            handleDatabaseError(res, err);
                            return;                    
                        }
                        
                        else if (roleName != 'Artist') {
                            //redirectToMainPage(res);

                            // Serve index.html
                            const htmlPath = path.join(__dirname, '..', 'client', 'index.html');
                            fs.readFile(htmlPath, function(err, data) {
                                if (err) {
                                    res.writeHead(404, {'Content-Type': 'text/plain'});
                                    res.end('File not found');
                                }
                                else {
                                    res.writeHead(200, {'Content-Type': 'text/html'});
                                    res.write(data);

                                    // Serve assosciated css file
                                    const cssPath = path.join(__dirname, '..', 'client', 'mainPage.css');
                                    fs.readFile(cssPath, 'utf-8', function(err, cssData) {
                                        if (!err) {
                                            res.write('\n<style>\n' + cssData + '\n</style>');
                                        }
                                        else {
                                            console.error('Error reading CSS file:', err);
                                        }

                                        // Serve assosciated js file
                                        const jsPath = path.join(__dirname, '..', 'client', 'mainPage.js');
                                        fs.readFile(jsPath, 'utf-8', function(err, jsData) {
                                            if (!err) {
                                                res.write('\n<script>\n' + jsData + '\n</script>');
                                            }
                                            else {
                                                console.error('Error reading js file:', err);
                                            }
                                            
                                            // End the response
                                            res.end();
                                        })
                                    })
                                }
                            });

                            console.log('You must be an artist to upload music!!!');
                            // alert js
                            return;
                        }
                    })
                    
                    getUserName(userID, (err, userName) => {
                        // Database connection error handler
                        if (err) {
                            handleDatabaseError(res, err);
                            return;                    
                        }

                        // Access form fields
                        const singleTitle = fields.singleTitle[0];
                        const singleGenre = fields.singleGenre[0];

                        // Access file information
                        const singleCoverFile = files.singleCover;
                        const singleFile = files.singleFile;

                        // User didn't select a cover; assign the default one*
                        let coverFileContent = null;
                        if (!singleCoverFile || singleCoverFile[0].size === 0) {
                            console.log('No cover file selected.');
                        }

                        // Read cover file content as binary data to prepare to store in the Database
                        else {
                            const singleCoverFilePath = singleCoverFile[0].filepath;
                            coverFileContent = fs.readFileSync(singleCoverFilePath);
                        }
                        
                        const singleFilePath = singleFile[0].filepath;
                        const singleFileOriginalFilename = singleFile[0].originalFilename;
    
                        // if errors in data, redirect user to page with a back button so that they can modify accordingly
                        if (!singleFileOriginalFilename.endsWith('.mp3')) {
                            console.log('Only .mp3 files supported');
                            // Redirect to form page
                            redirectToMusicUpload(res);
                            return;
                        }                        
    
                        // Read single file content as binary data
                        const singleFileContent = fs.readFileSync(singleFilePath);
                        
    
                        // Once confirmed user is an artist with no data entry errors, we will INSERT INTO the album / song tables accordingly
                        sql.connect(dbConfig, (err) => {
                            // Database connection error handler
                            if (err) {
                                handleDatabaseError(res, err);
                                return;                    
                            }
    
                            const request = new sql.Request();
    
                            // Define the SQL query with OUTPUT clause to get the inserted ID to then use for Song query
                            const query = 
                            `INSERT INTO MusicLibrary.[Album] (Title, Artist, Genre, Cover, Release_Year, Number_Of_Songs, Created_By)
                            OUTPUT INSERTED.Album_ID
                            VALUES (@singleTitle, @artistName, @singleGenre, @singleCoverFile, '2023', 1, @artistID);`;

                            // Set parameters for the query
                            request.input('singleTitle', sql.VarChar, singleTitle);
                            request.input('artistName', sql.VarChar, userName);
                            request.input('singleGenre', sql.VarChar, singleGenre);
                            request.input('singleCoverFile', sql.VarBinary, coverFileContent);
                            request.input('artistID', sql.Int, userID);
    
                            let insertedID;
    
                            request.query(query, (err, result) =>  {
                                if (err) {                                                   // Database query error handler
                                    console.error('Database query error:', err);
                                    sql.close();
                                    res.writeHead(500, { 'Content-Type': 'text/plain' });
                                    res.end('Database query error');
                                    return;
                                }

                                // Process query result and get inserted Album_ID
                                insertedID = result.recordset[0].Album_ID;
                                console.log('Query insert result (1):', insertedID);

                                const secondRequest = new sql.Request();
    
                                // Define the SQL query with OUTPUT clause to get the inserted ID to then use for Song query
                                const secondQuery = 
                                `INSERT INTO MusicLibrary.[Song] (Album_ID, Title, Artist, Genre, Cover, Release_Year, Marked_For_Deletion, Created_By, Audio_Data)
                                OUTPUT INSERTED.Song_ID
                                VALUES (@insertedID, @singleTitle, @artistName, @singleGenre, @singleCoverFile, '2023', 0, @createdBy, @singleFile);`;
        
                                // Set parameters for the query
                                secondRequest.input('insertedID', sql.Int, insertedID);
                                secondRequest.input('singleTitle', sql.VarChar, singleTitle);
                                secondRequest.input('artistName', sql.VarChar, userName);
                                secondRequest.input('singleGenre', sql.VarChar, singleGenre);
                                secondRequest.input('singleCoverFile', sql.VarBinary, coverFileContent);
                                secondRequest.input('createdBy', sql.Int, userID);
                                secondRequest.input('singleFile', sql.VarBinary, singleFileContent);
        
        
                                secondRequest.query(secondQuery, (err, secondResult) =>  {
                                    if (err) {                                                   // Database query error handler
                                        console.error('Database query error:', err);
                                        sql.close();
                                        res.writeHead(500, { 'Content-Type': 'text/plain' });
                                        res.end('Database query error');
                                        return;
                                    }

                                    // Process query result and get inserted Song_ID
                                    var singleID = secondResult.recordset[0].Song_ID;
                                    console.log('Query insert result (2):', singleID);
                                    sql.close();
                                })
                            })
                        })
                    })
                })
            res.end();
        }

        else if (fileName === '/artistDataEntry/album') {
            // Data parsing
            let body = '';
            req.on('data', (data) => {
                body += data.toString();
            });

            // Attempts to authenticate a user's session; if not authentic (session doesn't match server memory, or session doesn't exist) then user is sent to login page
            // Also retrieves userID if session in cookie matches session in memory
            const user = { id: undefined };
            let certified = authenticateSession(req, res, user);

            if (!certified) {
                return;
            }

            var userID = user.id;

            // Data Validation 
            const form = new formidable.IncomingForm({
                // Allow empty files when parsing form
                allowEmptyFiles: true,
                minFileSize: 0
            });

            //form.uploadDir = __dirname + '/uploads';

                form.parse(req, (err, fields, files) => {
                    if (err) {
                        console.error('Error parsing form:', err);
                        res.writeHead(500, { 'Content-Type': 'text/plain' });
                        res.end('Internal Server Error');
                        return;
                    }

                    // Security authentication (user must be an artist)
                    getUserRole(userID, (err, roleName) => {
                        // Database connection error handler
                        if (err) {
                            handleDatabaseError(res, err);
                            return;                    
                        }
                        
                        else if (roleName != 'Artist') {
                            //redirectToMainPage(res);
                            // Serve index.html
                            const htmlPath = path.join(__dirname, '..', 'client', 'index.html');
                            fs.readFile(htmlPath, function(err, data) {
                                if (err) {
                                    res.writeHead(404, {'Content-Type': 'text/plain'});
                                    res.end('File not found');
                                }
                                else {
                                    res.writeHead(200, {'Content-Type': 'text/html'});
                                    res.write(data);

                                    // Serve assosciated css file
                                    const cssPath = path.join(__dirname, '..', 'client', 'mainPage.css');
                                    fs.readFile(cssPath, 'utf-8', function(err, cssData) {
                                        if (!err) {
                                            res.write('\n<style>\n' + cssData + '\n</style>');
                                        }
                                        else {
                                            console.error('Error reading CSS file:', err);
                                        }

                                        // Serve assosciated js file
                                        const jsPath = path.join(__dirname, '..', 'client', 'mainPage.js');
                                        fs.readFile(jsPath, 'utf-8', function(err, jsData) {
                                            if (!err) {
                                                res.write('\n<script>\n' + jsData + '\n</script>');
                                            }
                                            else {
                                                console.error('Error reading js file:', err);
                                            }
                                            
                                            // End the response
                                            res.end();
                                        })
                                    })
                                }
                            });

                            console.log('You must be an artist to upload music!!!');
                            // alert js
                            return;
                        }
                    })
                    
                    getUserName(userID, (err, userName) => {
                        // Database connection error handler
                        if (err) {
                            handleDatabaseError(res, err);
                            return;                    
                        }

                        // Access form fields
                        const albumTitle = fields.albumTitle[0];
                        const albumGenre = fields.albumGenre[0];
                        const albumSongs = fields.albumSongs[0];

                        // Access file information
                        const albumCoverFile = files.albumCover;

                        // Get all songs' information
                        const songs = [];

                        for (let i = 1; i <= albumSongs; i++) {
                            // Access each song's title and file
                            const songTitle = fields[`songTitle${i}`][0];
                            const songFile = files[`songFile${i}`];
                        
                            const songFilePath = songFile[0].filepath;
                            const songFileOriginalFilename = songFile[0].originalFilename;
        
                            // if errors in data, redirect user to page with a back button so that they can modify accordingly
                            if (!songFileOriginalFilename.endsWith('.mp3')) {
                                console.log('Only .mp3 files supported');
                                // Redirect to form page
                                redirectToMusicUpload(res);
                                return;
                            }

                            // Read single file content as binary data
                            const songFileContent = fs.readFileSync(songFilePath);

                            // Create an object with title and file information
                            const songDetails = {
                                title: songTitle,
                                content: songFileContent
                            };
                        
                            // Push the song details object to the songs array
                            songs.push(songDetails);
                        }

                        // User didn't select a cover; assign the default one*
                        let coverFileContent = null;
                        if (!albumCoverFile || albumCoverFile[0].size === 0) {
                            console.log('No cover file selected.');
                        }

                        // Read cover file content as binary data to prepare to store in the Database
                        else {
                            const albumCoverFilePath = albumCoverFile[0].filepath;
                            coverFileContent = fs.readFileSync(albumCoverFilePath);
                        }                        
    
                        // Once confirmed user is an artist with no data entry errors, we will INSERT INTO the album / song tables accordingly
                        sql.connect(dbConfig, (err) => {
                            // Database connection error handler
                            if (err) {
                                handleDatabaseError(res, err);
                                return;                    
                            }
    
                            const request = new sql.Request();
    
                            // Define the SQL query with OUTPUT clause to get the inserted ID to then use for Song query
                            const query = 
                            `INSERT INTO MusicLibrary.[Album] (Title, Artist, Genre, Cover, Release_Year, Number_Of_Songs, Created_By)
                            OUTPUT INSERTED.Album_ID
                            VALUES (@albumTitle, @artistName, @albumGenre, @albumCoverFile, '2023', @albumSongs, @artistID);`;

                            // Set parameters for the query
                            request.input('albumTitle', sql.VarChar, albumTitle);
                            request.input('artistName', sql.VarChar, userName);
                            request.input('albumGenre', sql.VarChar, albumGenre);
                            request.input('albumCoverFile', sql.VarBinary, coverFileContent);
                            request.input('albumSongs', sql.Int, albumSongs);
                            request.input('artistID', sql.Int, userID);
    
                            let insertedID;
    
                            request.query(query, (err, result) =>  {
                                if (err) {                                                   // Database query error handler
                                    console.error('Database query error:', err);
                                    sql.close();
                                    res.writeHead(500, { 'Content-Type': 'text/plain' });
                                    res.end('Database query error');
                                    return;
                                }

                                // Process query result and get inserted Album_ID
                                insertedID = result.recordset[0].Album_ID;
                                console.log('Query insert result (1):', insertedID);

                                // Inserts for every song
                                Promise.all(
                                    songs.map(song => {
                                        return new Promise((resolve, reject) => {
                                            const secondRequest = new sql.Request();
                                            const secondQuery = `
                                            INSERT INTO MusicLibrary.[Song] (Album_ID, Title, Artist, Genre, Cover, Release_Year, Marked_For_Deletion, Created_By, Audio_Data)
                                            OUTPUT INSERTED.Song_ID
                                            VALUES (@insertedID, @songTitle, @artistName, @albumGenre, @albumCoverFile, '2023', 0, @createdBy, @songFile);
                                            `;
                                    
                                            secondRequest.input('insertedID', sql.Int, insertedID);
                                            secondRequest.input('songTitle', sql.VarChar, song.title);
                                            secondRequest.input('artistName', sql.VarChar, userName);
                                            secondRequest.input('albumGenre', sql.VarChar, albumGenre);
                                            secondRequest.input('albumCoverFile', sql.VarBinary, coverFileContent);
                                            secondRequest.input('createdBy', sql.Int, userID);
                                            secondRequest.input('songFile', sql.VarBinary, song.content);
                                    
                                            secondRequest.query(secondQuery, (err, secondResult) => {
                                                if (err) {
                                                    console.error('Database query error:', err);
                                                    reject(err);
                                                }
                                                else {
                                                    var songID = secondResult.recordset[0].Song_ID;
                                                    console.log('Query insert result (2):', songID);
                                                    resolve(songID);
                                                }
                                            });
                                        });
                                    })
                                )
                                .then(() => {
                                    // All song insertion queries have finished
                                    sql.close();
                                })
                                .catch(error => {
                                    console.error('Error inserting songs:', error);
                                    sql.close();
                                    res.writeHead(500, { 'Content-Type': 'text/plain' });
                                    res.end('Error inserting songs');
                                });
                            })
                        })
                    })
                })
            res.end();
        }

        else if(fileName === '/artistDataReport') {
            // Data parsing
            let body = '';
            req.on('data', (data) => {
                body += data.toString();
            });

            // Attempts to authenticate a user's session; if not authentic (session doesn't match server memory, or session doesn't exist) then user is sent to login page
            // Also retrieves userID if session in cookie matches session in memory
            const user = { id: undefined };
            let certified = authenticateSession(req, res, user);

            if (!certified) {
                return;
            }

            var userID = user.id;

            // Data Validation 
            const form = new formidable.IncomingForm();
            console.log(form);
            form.parse(req, (err, fields) => {
                if (err) {
                    console.error('Error parsing form:', err);
                    res.writeHead(500, { 'Content-Type': 'text/plain' });
                    res.end('Internal Server Error');
                    return;
                }
                // Access form fields
                const albumParameter = fields.selection[0];
                // Sets albumTitle parameter accordingly
                let albumTitle;
                if (albumParameter === 'allAlbums') {
                    albumTitle = '%';
                }
                else {
                    albumTitle = fields.albumTitle[0];
                }

                // Sets state parameter accordingly
                let state = fields.state[0];
                if (state === 'ALL') {
                    state = '%';
                }

                const minRating = fields.minimumRating[0];
                const maxRating = fields.maximumRating[0];
                const minListens = fields.minimumListens[0];
                const maxListens = fields.maximumListens[0];
                const fromDate = fields.fromDate[0];
                const toDate = fields.toDate[0];

                console.log('userID', userID);
                console.log('albumTitle', albumTitle);
                console.log('state', state);
                console.log('minRating', minRating);
                console.log('maxRating', maxRating);
                console.log('minListens', minListens);
                console.log('maxListens', maxListens);
                console.log('fromDate', fromDate);
                console.log('toDate', toDate);

                sql.connect(dbConfig, (err) => {
                    // Database connection error handler
                    if (err) {
                        handleDatabaseError(res, err);
                        return;                    
                    }

                    const request = new sql.Request();
                    
                    // const query = `SELECT A.Title, A.Times_Played, A.Rating, A.Genre FROM MusicLibrary.[Song] A;`;

                    
                    // Defining SELECT query to pass back to html form to display as a grid
                    const query = 
                    `SELECT DISTINCT A.Title, A.Times_Played, A.Rating, A.Genre, FORMAT(A.Created_At, 'MM/dd/yyyy') AS Created_Date
                    FROM MusicLibrary.[Song] A, MusicLibrary.[Album] B, MusicLibrary.[User_Song_Rating] D, MusicLibrary.[Listener] E, MusicLibrary.[User] F
                    WHERE F.Cougar_ID = @artistID
                    AND F.Role_ID = 2
                    AND B.Created_By = F.Cougar_ID
                    AND A.Album_ID = B.Album_ID
                    AND A.Song_ID = D.Song_ID
                    AND D.Cougar_ID = E.Cougar_ID
                    AND E.[State] LIKE @state
                    AND B.Title LIKE @album
                    AND A.Rating BETWEEN @minRating AND @maxRating
                    AND A.Times_Played BETWEEN @minListens AND @maxListens
                    AND A.Created_At BETWEEN CONVERT(datetime2, @fromDate) AND CONVERT(datetime2, @toDate);`

                    // Set parameters for the query
                    request.input('artistID', sql.Int, userID);
                    request.input('state', sql.VarChar, state);
                    request.input('album', sql.VarChar, albumTitle);
                    request.input('minRating', sql.Int, minRating);
                    request.input('maxRating', sql.Int, maxRating);
                    request.input('minListens', sql.Int, minListens);
                    request.input('maxListens', sql.Int, maxListens);
                    request.input('fromDate', sql.DateTime2, fromDate);
                    request.input('toDate', sql.DateTime2, toDate);

                    // Process query result and store it to use as a response
                    request.query(query, (err, result) =>  {
                        if (err) {                                                   // Database query error handler
                            console.error('Database query error:', err);
                            sql.close();
                            res.writeHead(500, { 'Content-Type': 'text/plain' });
                            res.end('Database query error');
                            return;
                        }
                        // Collects rows of data and stores it as JSON to send back to the client
                        const rows = result.recordset;
                        const jsonData = JSON.stringify(rows);
                        res.writeHead(200, {
                            'Content-Type': 'application/json',
                            'Content-Length': Buffer.byteLength(jsonData, 'utf8')
                        });

                        console.log(jsonData);
                        res.end(jsonData);
                    })
                })
            })
        }

        else if(fileName === '/adminDataReport') {
            // Data parsing
            let body = '';
            req.on('data', (data) => {
                body += data.toString();
            });

            // Attempts to authenticate a user's session; if not authentic (session doesn't match server memory, or session doesn't exist) then user is sent to login page
            // Also retrieves userID if session in cookie matches session in memory
            const user = { id: undefined };
            let certified = authenticateSession(req, res, user);

            if (!certified) {
                return;
            }

            var userID = user.id;

            // Data Validation 
            const form = new formidable.IncomingForm();
            console.log(form);
            form.parse(req, (err, fields) => {
                
                if (err) {
                    console.error('Error parsing form:', err);
                    res.writeHead(500, { 'Content-Type': 'text/plain' });
                    res.end('Internal Server Error');
                    return;
                }
                // Access form fields
                console.log('Fields are:')
                console.log(fields)
                const number_of_artists_to_include = fields.number_of_artists_to_include;
                
                var city = false;
                if (fields.city){
                    city = true; // if city will be included
                }
                
                const genre = fields.genre;

                var show_name_of_most_famous_song = false;
                if (fields.show_name_of_most_famous_song){
                    show_name_of_most_famous_song = true;
                }

                console.log(number_of_artists_to_include);
                console.log(city);
                console.log(genre);
                console.log(show_name_of_most_famous_song);
            })
        }

        // No file exists for this POST method
        else {
            res.writeHead(404, {'Content-Type': 'text/plain'});
            res.end('Not Found');
        }
    }

    // We can create functions / modules outside of this app for better organization maybe
    else if (req.method === 'GET') {
        console.log('File path for GET request:', fileName);
        // Keep as template for now, create branch for your html doc
        
        if (fileName === '/login/musicUpload.html') {

            // Attempts to authenticate a user's session; if not authentic (session doesn't match server memory, or session doesn't exist) then user is sent to login page
            // Also retrieves userID if session in cookie matches session in memory
            const user = { id: undefined };
            let certified = authenticateSession(req, res, user);

            if (!certified) {
                return;
            }

            var userID = user.id;
            
            // Data Validation / Security authentication (user must be an artist)
            getUserRole(userID, (err, roleName) => {
                // Database connection error handler
                if (err) {
                    handleDatabaseError(res, err);
                    return;                    
                }
                
                else if (roleName != 'Artist') {
                    //redirectToMainPage(res);

                    // Serve index.html
                    const htmlPath = path.join(__dirname, '..', 'client', 'index.html');
                    fs.readFile(htmlPath, function(err, data) {
                        if (err) {
                            res.writeHead(404, {'Content-Type': 'text/plain'});
                            res.end('File not found');
                        }
                        else {
                            res.writeHead(200, {'Content-Type': 'text/html'});
                            res.write(data);

                            // Serve assosciated css file
                            const cssPath = path.join(__dirname, '..', 'client', 'mainPage.css');
                            fs.readFile(cssPath, 'utf-8', function(err, cssData) {
                                if (!err) {
                                    res.write('\n<style>\n' + cssData + '\n</style>');
                                }
                                else {
                                    console.error('Error reading CSS file:', err);
                                }

                                // Serve assosciated js file
                                const jsPath = path.join(__dirname, '..', 'client', 'mainPage.js');
                                fs.readFile(jsPath, 'utf-8', function(err, jsData) {
                                    if (!err) {
                                        res.write('\n<script>\n' + jsData + '\n</script>');
                                    }
                                    else {
                                        console.error('Error reading js file:', err);
                                    }
                                    
                                    // End the response
                                    res.end();
                                })
                            })
                        }
                    });

                    console.log('You must be an artist to upload music!!!');
                    // alert js
                    return;
                }

                // Serve musicUpload.html
                const musicUploadHtmlPath = path.join(__dirname, '..', 'client', 'musicUpload.html');
                const writeHeadParameters = [200, { 'Content-Type': 'text/html; charset=utf-8' }];

                serveFile(res, 1, writeHeadParameters, musicUploadHtmlPath);
            })
            return; // Return to avoid further processing for this route
        }

        else if (fileName === '/getAlbumID') {
            const userCookie = req.headers.cookie;
            let userID = getIdFromCookie(userCookie)

            let recommendedAlbum;
            getRecommendedAlbum(userID, (err, recommendedAlbum) => {
                if (err) {
                    console.error('Error:', err);
                    res.status(500).json({ error: 'Server error' });
                    return;
                }

                console.log('Recommended Album: ', recommendedAlbum);
                if (recommendedAlbum) {
                    res.writeHead(200, { 'Content-Type': 'application/json' });
                    res.end(JSON.stringify({ recommendedAlbum }));
                }
                else {
                    res.writeHead(200, { 'Content-Type': 'application/json' });
                    res.end(JSON.stringify({ recommendedAlbum: null }));
                }
            })
        }

        else if (fileName === '/login/artistDataReport.html') {
            const user = { id: undefined };
            let certified = authenticateSession(req, res, user);

            if (!certified) {
                return;
            }

            var userID = user.id;
            
            // Security authentication (user must be an artist)
            getUserRole(userID, (err, roleName) => {
                // Database connection error handler
                if (err) {
                    handleDatabaseError(res, err);
                    return;                    
                }
                
                else if (roleName != 'Artist') {
                    //redirectToMainPage(res);

                    // Serve index.html
                    const htmlPath = path.join(__dirname, '..', 'client', 'index.html');
                    fs.readFile(htmlPath, function(err, data) {
                        if (err) {
                            res.writeHead(404, {'Content-Type': 'text/plain'});
                            res.end('File not found');
                        }
                        else {
                            res.writeHead(200, {'Content-Type': 'text/html'});
                            res.write(data);

                            // Serve assosciated css file
                            const cssPath = path.join(__dirname, '..', 'client', 'mainPage.css');
                            fs.readFile(cssPath, 'utf-8', function(err, cssData) {
                                if (!err) {
                                    res.write('\n<style>\n' + cssData + '\n</style>');
                                }
                                else {
                                    console.error('Error reading CSS file:', err);
                                }

                                // Serve assosciated js file
                                const jsPath = path.join(__dirname, '..', 'client', 'mainPage.js');
                                fs.readFile(jsPath, 'utf-8', function(err, jsData) {
                                    if (!err) {
                                        res.write('\n<script>\n' + jsData + '\n</script>');
                                    }
                                    else {
                                        console.error('Error reading js file:', err);
                                    }
                                    
                                    // End the response
                                    res.end();
                                })
                            })
                        }
                    });

                    console.log('You must be an artist to see artist reports!!!');
                    // alert js
                    return;
                }

                const artistDataReportHtmlPath = path.join(__dirname, '..', 'client', 'artistDataReport.html');
                const writeHeadParameters = [200, { 'Content-Type': 'text/html; charset=utf-8' }];

                // Serve playlist.html
                serveFile(res, 1, writeHeadParameters, artistDataReportHtmlPath);
            })
            return; // Return to avoid further processing for this route
        }

        else if (fileName === '/login.html') {
            const filePath = path.join(__dirname, '..', 'client', 'login.html');

            // Serve login.html
            redirectToLoginPage(res);

            // Connect to database

            // Do user account authentication to ensure they have access to see report (if they are an artist and the report is for their music)/ playlist (if hidden but they are the owner), etc.

            // If no access, close connection and output appropriate message to them

            // Else, do a request.query('SELECT thing_1, thing_2, etc., FROM table_1, table_2, WHERE conditions', ...) to pull rows of data. Next, find out how to modify page to showcase data pulled (may need to use fs object)

            return; // Return to avoid further processing for this route
        }

        else if (fileName === '/login/login.html') {
            const filePath = path.join(__dirname, '..', 'client', 'login.html');
            // Authenticates user session
            const user = { id: undefined };
            let certified = authenticateSession(req, res, user);

            if (!certified) {
                return;
            }

            var userID = user.id;
            // Serve login.html
            redirectToLoginPage(res);

            // Connect to database

            // Do user account authentication to ensure they have access to see report (if they are an artist and the report is for their music)/ playlist (if hidden but they are the owner), etc.

            // If no access, close connection and output appropriate message to them

            // Else, do a request.query('SELECT thing_1, thing_2, etc., FROM table_1, table_2, WHERE conditions', ...) to pull rows of data. Next, find out how to modify page to showcase data pulled (may need to use fs object)

            return; // Return to avoid further processing for this route
        }

        else if (fileName === '/login/admin.html') {

            const user = { id: undefined };
            let certified = authenticateSession(req, res, user);

            if (!certified) {
                return;
            }

            var userID = user.id;
            
            // Security authentication (user must be an admin)
            getUserRole(userID, (err, roleName) => {
                // Database connection error handler
                if (err) {
                    handleDatabaseError(res, err);
                    return;                    
                }
                
                else if (roleName != 'Admin') {
                    //redirectToMainPage(res);

                    // Serve index.html
                    const htmlPath = path.join(__dirname, '..', 'client', 'index.html');
                    fs.readFile(htmlPath, function(err, data) {
                        if (err) {
                            res.writeHead(404, {'Content-Type': 'text/plain'});
                            res.end('File not found');
                        }
                        else {
                            res.writeHead(200, {'Content-Type': 'text/html'});
                            res.write(data);

                            // Serve assosciated css file
                            const cssPath = path.join(__dirname, '..', 'client', 'mainPage.css');
                            fs.readFile(cssPath, 'utf-8', function(err, cssData) {
                                if (!err) {
                                    res.write('\n<style>\n' + cssData + '\n</style>');
                                }
                                else {
                                    console.error('Error reading CSS file:', err);
                                }

                                // Serve assosciated js file
                                const jsPath = path.join(__dirname, '..', 'client', 'mainPage.js');
                                fs.readFile(jsPath, 'utf-8', function(err, jsData) {
                                    if (!err) {
                                        res.write('\n<script>\n' + jsData + '\n</script>');
                                    }
                                    else {
                                        console.error('Error reading js file:', err);
                                    }
                                    
                                    // End the response
                                    res.end();
                                })
                            })
                        }
                    });

                    console.log('You must be an admin to navigate to this page!!!');
                    // alert js
                    return;
                }

                // Serve admin page
                const htmlFilePath = path.join(__dirname, '..', 'client', 'admin.html');
                fs.readFile(htmlFilePath, function(err, data) {
                    if (err) {
                        res.writeHead(404, {'Content-Type': 'text/plain'});
                        res.end('File not found');
                    }
                    else {
                        res.writeHead(200, {'Content-Type': 'text/html'});
                        res.write(data);
                        res.end();
                    }
                });
            })
            return; // Return to avoid further processing for this route
        }

        else if (fileName === '/login/settings_page/index.html') {
            const user = { id: undefined };
            let certified = authenticateSession(req, res, user);

            if (!certified) {
                return;
            }

            var userID = user.id;

            // Serve settings page
            const htmlFilePath = path.join(__dirname, '..', 'client', 'settings_page','index.html');
            fs.readFile(htmlFilePath, function(err, data) {
                if (err) {
                    res.writeHead(404, {'Content-Type': 'text/plain'});
                    res.end('File not found');
                }
                else {
                    res.writeHead(200, {'Content-Type': 'text/html'});
                    res.write(data);

                    // Serve assosciated css file
                    const cssFilePath = path.join(__dirname, '..', 'client', 'settings_page','stylesheet.css');
                    fs.readFile(cssFilePath, 'utf-8', function(err, cssData) {
                        if (!err) {
                            res.write('\n<style>\n' + cssData + '\n</style>');
                        }
                        else {
                            console.error('Error reading CSS file:', err);
                        }

                        // Serve assosciated js file
                        const jsFilePath = path.join(__dirname, '..', 'client', 'settings_page','script.js');
                        fs.readFile(jsFilePath, 'utf-8', function(err, jsData) {
                            if (!err) {
                                res.write('\n<script>\n' + jsData + '\n</script>');
                            }
                            else {
                                console.error('Error reading js file:', err);
                            }
                            
                            // End the response
                            res.end();
                        })
                    })
                }
            });

            return; // Return to avoid further processing for this route
        }

        else if (fileName === '/login/index.html') {

            // Attempts to authenticate a user's session; if not authentic (session doesn't match server memory, or session doesn't exist) then user is sent to login page
            // Also retrieves userID if session in cookie matches session in memory
            const user = { id: undefined };
            let certified = authenticateSession(req, res, user);

            if (!certified) {
                return;
            }

            var userID = user.id;
            
            // Serve index.html
            const htmlPath = path.join(__dirname, '..', 'client', 'index.html');
            fs.readFile(htmlPath, function(err, data) {
                if (err) {
                    res.writeHead(404, {'Content-Type': 'text/plain'});
                    res.end('File not found');
                }
                else {
                    res.writeHead(200, {'Content-Type': 'text/html'});
                    res.write(data);

                    // Serve assosciated css file
                    const cssPath = path.join(__dirname, '..', 'client', 'mainPage.css');
                    fs.readFile(cssPath, 'utf-8', function(err, cssData) {
                        if (!err) {
                            res.write('\n<style>\n' + cssData + '\n</style>');
                        }
                        else {
                            console.error('Error reading CSS file:', err);
                        }

                        // Serve assosciated js file
                        const jsPath = path.join(__dirname, '..', 'client', 'mainPage.js');
                        fs.readFile(jsPath, 'utf-8', function(err, jsData) {
                            if (!err) {
                                res.write('\n<script>\n' + jsData + '\n</script>');
                            }
                            else {
                                console.error('Error reading js file:', err);
                            }
                            
                            // End the response
                            res.end();
                        })
                    })
                }
            });
            
            // Connect to database

            // Do user account authentication to ensure they have access to see report (if they are an artist and the report is for their music)/ playlist (if hidden but they are the owner), etc.

            // If no access, close connection and output appropriate message to them

            // Else, do a request.query('SELECT thing_1, thing_2, etc., FROM table_1, table_2, WHERE conditions', ...) to pull rows of data. Next, find out how to modify page to showcase data pulled (may need to use fs object)

            return; // Return to avoid further processing for this route
        }
        
        else if (fileName === '/login/playlist.html') {
            const playlistHtmlPath = path.join(__dirname, '..', 'client', 'playlist.html');
            const playlistCssFileName = 'playlist.css';
            const playlistJsFileName = 'playlist.js';
            const writeHeadParameters = [200, { 'Content-Type': 'text/html; charset=utf-8' }];

            // Serve playlist.html
            serveFile(res, 4, writeHeadParameters, playlistHtmlPath, playlistCssFileName, playlistJsFileName);
            
            // Connect to database

            // Do user account authentication to ensure they have access to see report (if they are an artist and the report is for their music)/ playlist (if hidden but they are the owner), etc.

            // If no access, close connection and output appropriate message to them

            // Else, do a request.query('SELECT thing_1, thing_2, etc., FROM table_1, table_2, WHERE conditions', ...) to pull rows of data. Next, find out how to modify page to showcase data pulled (may need to use fs object)

            return; // Return to avoid further processing for this route
        }

        else if (fileName === '/login/profile.html') {
            const profileHtmlPath = path.join(__dirname, '..', 'client', 'profile.html');
            const profileCssFileName = 'profile.css';
            const profileJsFileName = 'profile.js';
            const writeHeadParameters = [200, { 'Content-Type': 'text/html; charset=utf-8' }];

            // Serve profile.html
            serveFile(res, 4, writeHeadParameters, profileHtmlPath, profileCssFileName, profileJsFileName);

            // Connect to database

            // Do user account authentication to ensure they have access to see report (if they are an artist and the report is for their music)/ playlist (if hidden but they are the owner), etc.

            // If no access, close connection and output appropriate message to them

            // Else, do a request.query('SELECT thing_1, thing_2, etc., FROM table_1, table_2, WHERE conditions', ...) to pull rows of data. Next, find out how to modify page to showcase data pulled (may need to use fs object)

            return; // Return to avoid further processing for this route
        }
        // No file exists for this GET method
        else {
            res.writeHead(404, {'Content-Type': 'text/plain'});
            res.end('Not Found');
        }

        // else if (etc.)
    }
})

const PORT = process.env.PORT || 8080;

server.listen(PORT, () => {                                                      // Server object listens on this port
  console.log('Server is listening on port ' + PORT);
});